version: '3.6'
services:
  nhost-postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
  nhost-graphql-engine:
    image: hasura/graphql-engine:v1.1.0.cli-migrations
    ports:
      - '8080:8080'
    depends_on:
      - nhost-postgres
    restart: always
    environment:
      HASURA_GRAPHQL_SERVER_PORT: 8080
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@nhost-postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: f18910d5c47317dc6f497b760b550da8
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "bf03620661f7e0b8ac3e8f76388efed0accc5eb804779cd3b293b558766af2832da092b2ab15a51bdc4b22e785d9570ac05fd003dd7d694f818f60e47addc206"}'
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 5
      HASURA_GRAPHQL_NO_OF_RETRIES: 5
      SECRET_WEBHOOK_HEADER: ea2a05a734558d988fab5d6a435788982e7ebbe3017331753a6239f2a6e11da4
    command:
      - graphql-engine
      - serve
    volumes:
      - ./migrations:/hasura-migrations
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:v1.2.3
    ports:
      - '9000:9000'
    depends_on:
      - nhost-graphql-engine
    restart: always
    environment:
      PORT: 9000
      USER_FIELDS: ''
      USER_REGISTRATION_AUTO_ACTIVE: 'true'
      HASURA_GRAPHQL_ENDPOINT: http://nhost-graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: f18910d5c47317dc6f497b760b550da8
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "bf03620661f7e0b8ac3e8f76388efed0accc5eb804779cd3b293b558766af2832da092b2ab15a51bdc4b22e785d9570ac05fd003dd7d694f818f60e47addc206"}'
      AUTH_ACTIVE: 'true'
      AUTH_LOCAL_ACTIVE: 'true'
      REFRESH_TOKEN_EXPIRES: 43200
      JWT_TOKEN_EXPIRES: 15
